### ISSUE TITLE
Failed to resolve import "lenis" from "astro:scripts/page.js". Does the file exist?

### ISSUE THREAD

**Issue by lakshaybhushan** [JusticeMatthew/astro-lenis#1]
<img width="1389" alt="image" src="https://github.com/JusticeMatthew/astro-lenis/assets/74349407/d6a75228-cd47-4e0e-8cfa-dd48289ea52e">

Hey do you how to fix this issue?

I'm sharing my astro config file:

```js
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import tailwind from "@astrojs/tailwind";
import vercel from "@astrojs/vercel/serverless";
import rehypePrettyCode from "rehype-pretty-code";
import rehypeSlug from "rehype-slug";
import mdx from "@astrojs/mdx";

import lenis from "astro-lenis";

// https://astro.build/config
export default defineConfig({
  output: "hybrid",
  integrations: [react(), tailwind(), mdx({
    syntaxHighlight: false,
    rehypePlugins: [rehypeSlug, [rehypePrettyCode, {
      theme: "houston"
    }]]
  }), lenis()],
  adapter: vercel({
    webAnalytics: {
      enabled: true
    }
  })
});

```

**Comment by JusticeMatthew** [comment]
Hey there! Sorry about that :(

For some clarification did you install via the astro CLI or manually?

**Comment by lakshaybhushan** [comment]
I've tried both, but it's giving me the same error :(

**Comment by JusticeMatthew** [comment]
Alright I just bootstrapped a fresh project and installed it to make sure none of the recent Astro updates broke anything and I'm not getting any errors

Could you try moving the `lenis()` function call before the `mdx()` function call in your integrations array? (seems weird but the ordering has made a difference for some integrations before)

Additionally, I'm wondering if it it might be due to the hybrid server output, are you able to test it removing the `output` key and value or does that break things in other ways?

**Comment by JusticeMatthew** [comment]
Okay after touching base with some integrations experts you should be able to resolve it by installing `lenis` into your project with whatever package manager you are using

This is due to an issue with the `package.json` on my end that I am going to fix now !

**Comment by lakshaybhushan** [comment]
I appreciate your help! Everything is functioning correctly. 
Keep up the great work!!

You can check out my portfolio website, where I've used `astro-lenis` at [lakshb.dev](https://lakshb.dev)
